# Generated by Django 2.2.8 on 2019-12-11 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lib_Classe', models.CharField(max_length=10)),
                ('annee_Promo', models.CharField(max_length=9)),
            ],
        ),
        migrations.CreateModel(
            name='Groupe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lib_Groupe', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Sous_partie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lib_Partie', models.CharField(max_length=1)),
                ('type_Partie', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='TOEIC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lib_TOEIC', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Eleve',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('classe', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='site_web.Classe')),
                ('groupe', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='site_web.Groupe')),
            ],
        ),
        migrations.CreateModel(
            name='ScoreParPartie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('id_Eleve', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='site_web.Eleve')),
                ('id_SousPartie', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='site_web.Sous_partie')),
                ('id_TOEIC', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='site_web.TOEIC')),
            ],
            options={
                'unique_together': {('id_SousPartie', 'id_TOEIC', 'id_Eleve')},
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_Question', models.CharField(max_length=3)),
                ('reponse_Juste', models.CharField(max_length=1)),
                ('id_SousPartie', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='site_web.Sous_partie')),
                ('id_TOEIC', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='site_web.TOEIC')),
            ],
            options={
                'unique_together': {('id_Question', 'id_TOEIC')},
            },
        ),
    ]
