# Generated by Django 2.2.6 on 2019-10-29 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lib_Classe', models.CharField(max_length=10)),
                ('anner_Promo', models.CharField(max_length=4)),
            ],
        ),
    ]
