# Generated by Django 2.2.6 on 2019-10-29 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_web', '0002_classe'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classe',
            old_name='anner_Promo',
            new_name='annee_Promo',
        ),
    ]
