# Generated by Django 2.2.6 on 2019-10-29 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('site_web', '0003_auto_20191029_1844'),
    ]

    operations = [
        migrations.AddField(
            model_name='eleve',
            name='classe',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='site_web.Classe'),
            preserve_default=False,
        ),
    ]
