# Generated by Django 2.2.6 on 2019-10-29 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_web', '0004_eleve_classe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eleve',
            name='classe',
        ),
    ]
