# Generated by Django 2.2.6 on 2019-10-29 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('site_web', '0005_remove_eleve_classe'),
    ]

    operations = [
        migrations.AddField(
            model_name='eleve',
            name='classe',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='site_web.Classe'),
        ),
    ]
