# Generated by Django 2.2.6 on 2019-11-03 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('site_web', '0006_eleve_classe'),
    ]

    operations = [
        migrations.CreateModel(
            name='Date',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Groupe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lib_Groupe', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='TOEIC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LibelleTOEIC', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reponse_Juste', models.CharField(max_length=1)),
                ('id_Question', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='site_web.TOEIC')),
            ],
        ),
        migrations.AddField(
            model_name='eleve',
            name='groupe',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='site_web.Groupe'),
        ),
    ]
