# Generated by Django 2.2.6 on 2019-11-03 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_web', '0007_auto_20191103_1718'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eleve',
            name='id',
        ),
        migrations.AddField(
            model_name='eleve',
            name='num_INE',
            field=models.CharField(default=0, max_length=11, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
