# Generated by Django 2.2.6 on 2019-11-03 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('site_web', '0008_auto_20191103_1734'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sous_partie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lib_Partie', models.CharField(max_length=1)),
                ('type_Partie', models.CharField(max_length=15)),
            ],
        ),
        migrations.RenameField(
            model_name='question',
            old_name='id_Question',
            new_name='id_TOEIC',
        ),
        migrations.RenameField(
            model_name='toeic',
            old_name='LibelleTOEIC',
            new_name='lib_TOEIC',
        ),
        migrations.AddField(
            model_name='question',
            name='id_SousPartie',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='site_web.Sous_partie'),
        ),
    ]
