# Generated by Django 2.2.6 on 2019-11-03 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_web', '0009_auto_20191103_1746'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='id_Question',
            field=models.CharField(default=0, max_length=1),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='question',
            unique_together={('id_Question', 'id_TOEIC')},
        ),
    ]
