# Generated by Django 2.2.6 on 2019-11-03 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('site_web', '0010_auto_20191103_1751'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.CharField(max_length=2)),
                ('id_SousPartie', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='site_web.Sous_partie')),
                ('id_TOEIC', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='site_web.TOEIC')),
                ('num_Ine', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='site_web.Eleve')),
            ],
        ),
    ]
